@startuml

title Architecture

node Application{
    [Api]
    [Command]
    [Queries]
    [Database]
}

node DatabaseMigration{
    [DbUp]
}

database "SQL\n" {
    [Data]
}

Api -down->Command
Api -down->Queries
Command -down->Database
Queries -down->Database
Database -down->Data

DbUp -up->Data





@enduml